name: integration

on:
  push:
    branches: [master]

jobs:
  validate:
    uses: ./.github/workflows/_validate-npm.yml
  publish:
    uses: aeternity/github-actions/.github/workflows/_publish-ecr.yml@v2.3.1
    needs: [validate]
    secrets: inherit
  deploy:
    uses: aeternity/github-actions/.github/workflows/_deploy-gitops.yml@v2.3.1
    needs: [publish]
    secrets: inherit
    with:
      DEPLOY_ENV: stg
      DEPLOY_APP: ${{ github.event.repository.name }}
      DEPLOY_VERSION: ${{ github.ref_name }}
      DEPLOY_SUBDOMAIN: contracts
